# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CmdLine@2
  displayName: Download Library
  inputs:
    script: |
      ./download.sh > log.txt

- task: CmdLine@2
  displayName: Build Library
  inputs:
    script: |
      ./download.sh > log.txt