# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

jobs:

  # development.
  - job: development_build
    displayName: development build
    pool:
      vmImage: 'macos-latest'

    steps:
    - checkout: self
      fetchDepth: 1
      submodules: recursive

    - task: CmdLine@2
      displayName: Download Library
      inputs:
        script: |
          ./download.sh > download_log.txt

    - task: CmdLine@2
      displayName: Build Library
      inputs:
        script: |
          ./build.sh -e development > log.txt
          
    - task: PublishBuildArtifacts@1
      displayName: 'postprocess: Artifact Project'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'developmennt project'
        publishLocation: 'Container'

  # distribution.
  - job: distribution_build
    displayName: distribution build
    pool:
      vmImage: 'macos-latest'

    steps:
    - checkout: self
      fetchDepth: 1
      submodules: recursive

    - task: CmdLine@2
      displayName: Download Library
      inputs:
        script: |
          ./download.sh > download_log.txt

    - task: CmdLine@2
      displayName: Build Library
      inputs:
        script: |
          ./build.sh -e distribution > log.txt
          
    - task: PublishBuildArtifacts@1
      displayName: 'postprocess: Artifact Project'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'distribution project'
        publishLocation: 'Container'

